version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - quantum-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  auth_service:
    build:
      context: .
      dockerfile: services/auth_service/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017
      - JWT_SECRET_KEY=your-secret-key
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app/services/auth_service
    depends_on:
      - mongodb
    networks:
      - quantum-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  project_service:
    build:
      context: .
      dockerfile: services/project_service/Dockerfile
    ports:
      - "8002:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app/services/project_service
    depends_on:
      - mongodb
    networks:
      - quantum-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  registry_service:
    build:
      context: .
      dockerfile: services/registry_service/Dockerfile
    ports:
      - "8003:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app/services/registry_service
    depends_on:
      - mongodb
    networks:
      - quantum-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  marketplace_service:
    build:
      context: .
      dockerfile: services/marketplace_service/Dockerfile
    ports:
      - "8004:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app/services/marketplace_service
    depends_on:
      - mongodb
    networks:
      - quantum-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api_gateway:
    build:
      context: .
      dockerfile: services/api_gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8000
      - PROJECT_SERVICE_URL=http://project_service:8000
      - REGISTRY_SERVICE_URL=http://registry_service:8000
      - MARKETPLACE_SERVICE_URL=http://marketplace_service:8000
      - JWT_SECRET_KEY=your-secret-key
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    working_dir: /app/services/api_gateway
    depends_on:
      - auth_service
      - project_service
      - registry_service
      - marketplace_service
    networks:
      - quantum-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  quantum-net:
    driver: bridge

volumes:
  mongodb_data: 