apiVersion: v1
kind: ConfigMap
metadata:
  name: circuit-service-config
  namespace: quantum-hub
data:
  PORT: "8001"
  LOG_LEVEL: "INFO"
  POSTGRES_URI: "postgresql://quantumhub:${POSTGRES_PASSWORD}@postgresql.quantum-hub.svc.cluster.local:5432/circuit-db"
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circuit-service
  namespace: quantum-hub
  labels:
    app: circuit-service
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: circuit-service
  template:
    metadata:
      labels:
        app: circuit-service
        component: backend
    spec:
      containers:
      - name: circuit-service
        image: quantum-hub/circuit-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: circuit-service-config
        - secretRef:
            name: postgres-credentials
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: circuit-service
  namespace: quantum-hub
  labels:
    app: circuit-service
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: circuit-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: circuit-service-hpa
  namespace: quantum-hub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: circuit-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 