apiVersion: v1
kind: Namespace
metadata:
  name: quantum-hub
  labels:
    name: quantum-hub
    environment: production
    app.kubernetes.io/part-of: quantum-hub

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quantum-hub-quota
  namespace: quantum-hub
spec:
  hard:
    pods: "50"
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "20"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: quantum-hub-limits
  namespace: quantum-hub
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 50m
      memory: 64Mi
  - type: PersistentVolumeClaim
    max:
      storage: 500Gi
    min:
      storage: 1Gi 